### ISSUE TITLE
Add a basic example script

### ISSUE THREAD

**Issue by maksis** [zersetz-end/airdcpp-runscript-extension#5]
As this extension actually looks quite handy, I think that it would be great to have a basic example script in the README that would also show the export format. That would be helpful especially for people who are not that familiar with JavaScript (and help to get started faster).

**Comment by zersetz-end** [comment]
Good idea. Just not sure I should be the one providing examples as my JavaScript knowledge is pretty limited. I'll see what I can do. Can you provide any useful examples?

**Comment by maksis** [comment]
Ah, looks like you've already added something. Those definitely clear things up for me. 

I actually thought earlier that the script to be executed should export some kind of function as you have `Parameters` section in the README, even though it seems to refer to the way how the extension is implemented with AsyncFunction (I've never used it). Maybe there could be a clarification in that section that those are global variables available for the script to use.

**Comment by zersetz-end** [comment]
Do you think the method signatures clear things up?

**Comment by maksis** [comment]
I have no preference between functions and globals but the current way looks clear to me
