### ISSUE TITLE
ReferenceError: scriptFunction is not defined

### ISSUE THREAD

**Issue by nls44** [zersetz-end/airdcpp-runscript-extension#9]
https://github.com/zersetz-end/airdcpp-runscript-extension/blob/c820067579ac39861836087bf389fc572b93e744/src/trigger/Hook.js#L67

Please replace "scriptFunction" with "callback" - current code results in a ReferenceError when trying to add hooks.

**Comment by zersetz-end** [comment]
Hook subscribtions fixed in 1.2.10
